app:
  port: 3000
  name: 'user-graphql'
  description: 'GraphQL prototype Command'
  version: '1.0'
  document-path: '/api-doc'

log:
  level: 'silly'

nanoid:
  alphanum: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
  len: 11

api-services:
  photos:
    list-photo:
      url: https://jsonplaceholder.typicode.com/photos/1
      method: "GET"
      timeout: 5000
      reject-unauthorized: false

