openapi: 3.0.0
paths:
  /metrics:
    get:
      operationId: PrometheusController_index
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: user-graphql
  description: "[CQRS] Command"
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas: {}
