openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        "200":
          description: ""
  /metrics:
    get:
      operationId: PrometheusController_index
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: user-graphql
  description: GraphQL prototype Command
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas: {}
